### ISSUE TITLE
Publish version 1.0

### ISSUE THREAD

**Issue by twidi** [limpyd/redis-limpyd#105]
Some pull requests to include:

- [x] #100 "Prepare evolution"
- [x] #102 "Collection mini refactor"
- [x] #101 "Add range indexes"
- [x] #103 "Add multi-index compositions + DateTimeIndex
- [x] #104 "Rebuild indexes
- [x] #106 "Small pass on documentation"
- [x] #109 "Allow `__in=` filtering"
- [x] #110 "Correct and enhance slicing"
- [x] #113 "Migrate setup to setup.cfg"

Some things to do:

- [x] ensure limpyd-extensions works with last code
- [x] ensure limpyd-jobs works with last code
